name: 'Analogicus Janeway Simulation Action'
description: 'This action runs a simulation with `make all` in your repository'
branding:
  color: purple
  icon: layers

inputs:

runs:
    using: 'composite'
    steps:
      - name: Checkout tech
        run: cd ../ && git clone https://github.com/wulffern/tech_sky130A.git
      - name: Install cicsim
        run:  python3 -m pip install cicsim
      - name: Run Simulation
        run: |
          #sudo apt install -y pandoc
          echo "set ng_nomodcheck \nset skywaterpdk \n set num_threads=8 \n option noinit \n option klu \n optran 0 0 0 100p 2n 0 \n option opts" > $HOME/.spiceinit
          export PDK_ROOT=/opt/pdk/share/pdk
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/opt/eda/bin" >> $GITHUB_PATH
          export CIC_RANDOM_PLOTNAME=1
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/eda/lib
          export PATH=/opt/eda/bin:$HOME/.local/bin:$PATH
          make all
